config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects

  resources :tasks do
    resources :comments
  end
  root 'tasks#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :task
  belongs_to :user, primary_key: 'id', foreign_key: 'created_by'
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :project
	belongs_to :user
	has_many :comments, dependent: :destroy
	validates_presence_of :title, :summary, :due_date, :project_id
	self.per_page = 5

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tasks
  has_many :comments, foreign_key: 'created_by'    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout :layout_by_controller

  before_filter :authenticate_user!

  protected

  def layout_by_controller
    devise_controller? ? 'devise' : 'application'
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @task = Task.find(params[:task_id])
    @comment = @task.comments.create(comments_params)
    @comment.created_by = current_user.id
    #redirect_to tasks_path
    respond_to do |format|
      if @comment.save
        format.html {redirect_to @task, notice: 'Comment inserted succesfully'}
        format.js
      end
    end
  end

  private

  def comments_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all.order(:due_date).paginate(:page => params[:page])
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])
    @comments = @task.comments.order(created_at: :desc)
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.created_by_id = current_user.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
        format.js
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_url, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :summary, :due_date, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong><%= comment.user.email %></strong>: <%= comment.comment %><br>
  <i>(<%= comment.created_at.strftime('%d/%m/%Y %H:%M') %>)</i>
</p>

app/views/comments/create.js.erb
$("<%= escape_javascript(render @comment) %>").appendTo("#comments-list");
$("#comment_comment").val('');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project Management</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="row-fluid">
    <div class="span8 offset1">
      <div class="jumbotron">
        <div class="text-center">
          <h1>Project management</h1>
        </div>
          <div class="text-center">
            <%= link_to new_task_path, class: "btn btn-primary", remote: true do %>
              <span class="glyphicon glyphicon-plus-sign"></span>Add a task
            <% end %>
          </div>
          <div class = "text-center">
            <strong><%= current_user.email %></strong>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <span class="glyphicon glyphicon-off"></span>
            <% end %>
          </div>
          <div class = "text-center">

          </div>
      </div>
    </div>
  </div>
  <div class="container-fluid main-text">
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project Management</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="row-fluid">
    <div class="span8 offset1">
      <div class="jumbotron">
        <div class="text-center">
          <h1>Project management</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
      <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <%= yield %>
          </div>
      </div>
  </div>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_select :due_date, {:prompt => {:day => 'Επιλογή ημέρας', :month => 'Επιλογή μήνα', :year => 'Επιλογή έτους'}}, {:class => "date-select", } %>
  </div>
  <div class="field">
    <%= f.label :project %><br>
    <%= f.collection_select(:project_id, Project.all, :id, :description, {include_blank: true}, {class: 'form-control'}) %>
  </div>
  <div class="actions">
    <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
     <i class="icon-ok icon-white"></i> Save
    <% end %>
  </div>
<% end %>

app/views/tasks/_task_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header bg-success">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h3 class="modal-title">Δημιουργία task</h3>
    </div>
    <div class = "modal-body">
      <%= form_for(@task) do |f| %>

          <% if @task.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

              <ul>
              <% @task.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <%= f.label :title %><br>
            <%= f.text_field :title, class: "form-control" %>
          </div>
          <div class="field">
            <%= f.label :summary %><br>
            <%= f.text_area :summary, class: "form-control" %>
          </div>
          <div class="field">
            <%= f.label :project %><br>
            <%= f.collection_select(:project_id, Project.all, :id, :description, {include_blank: true}, {class: 'form-control'}) %>
          </div>
          <div class="field">
            <%= f.label :due_date %><br>
            <%= f.text_field :due_date, class: "form-control datepicker" %>
          </div>
          <div class="modal-footer">
            <div class="actions">
              <button type="button" class="btn btn-default" data-dismiss="modal">
                <span class="glyphicon glyphicon-remove"></span>Close
              </button>
              <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
               <i class="icon-ok icon-white glyphicon glyphicon-ok"></i> Save
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/tasks/_view_task_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header bg-success">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h3 class="modal-title"><%= @task.title %></h3>
    </div>
    <div class = "modal-body">
      <p>
        <strong>Summary:</strong>
        <%= simple_format(@task.summary, {}, wrapper_tag: "div") %>
      </p>

      <p>
        <strong>Due date:</strong>
        <%= @task.due_date.strftime("%d/%m/%Y") %>
      </p>

      <p>
        <strong>Project:</strong>
        <%= @task.project.description %>
      </p>
      <hr>
      <div id = "comments-list">
        <%= render @comments %>
      </div>
      <hr>
      <h4>Νέο σχόλιο:</h4>
      <%= form_for([@task, @task.comments.build], remote: true) do |f| %>
        <div class="field">
          <%= f.text_area :comment, class: "form-control" %>
        </div>
        <div class="actions">
          <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
           <i class="icon-ok icon-white glyphicon glyphicon-check"></i>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="modal-footer">
      <div class="actions">
        <button type="button" class="btn btn-default" data-dismiss="modal">
          <span class="glyphicon glyphicon-remove"></span>Close
        </button>
      </div>
    </div>
</div>

app/views/tasks/create.js.erb
<%- if @article.errors.any? %>
  console.log('Error');
  $('#dialog-form').html('<%= escape_javascript(render('form')) %>');
<%- else %>
  console.log('Created');
  $('#dialog-form').dialog('close');
  $('#dialog-form').remove();
  $('table').append('<%= escape_javascript(render(@task)) %>');
  $('table tr:last .modal').click(attatchModal());
<%- end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/edit.js.erb
$("#show-tasks-edit-dialog").html("<%= escape_javascript(render 'edit_task', :object => @task) %>");
$("#open-tasks-edit-dialog").modal('show');

app/views/tasks/index.html.erb
<h2>Tasks</h2 >

<table class = "table table-striped">
  <thead>
    <tr>
      <th>Τίτλος</th>
      <th>Project</th>
      <th>Εώς ημερομηνία</th>
      <th>Ημερομηνία δημιουργίας</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.title, task, remote: true %></td>
        <td><%= link_to task.project.description, task, remote: true if !task.project.nil? %></td>
        <td><%= link_to task.due_date.strftime("%d/%m/%Y"), task, remote: true %></td>
        <td><%= link_to task.created_at.strftime("%d/%m/%Y"), task, remote: true %></td>
        <td><%= link_to 'Επεξεργασία', edit_task_path(task), {class: "btn btn-primary"} %></td>
        <td><%= link_to 'Διαγραφή', task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @tasks, renderer: BootstrapPagination::Rails %>
<br>
<div class="modal fade" id="modal">
</div>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/new.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'task_form', locals: {task: @task}) %>');
m.modal('show');
$('#modal').integrateDatepicker();

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @task.summary %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @task.due_date %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/show.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'view_task_form', locals: {task: @task}) %>');
m.modal('show');